### ISSUE TITLE
Normalize directory names to be compatible with new pip standard

### ISSUE THREAD

**Issue by orodbhen** [wolever/pip2pi#34]
In pip 6, handling of mixed-case directory names under simple/ is deprecated, and will result in a warning message. See [this commit](https://github.com/pypa/pip/commit/f72a9042f9c8267170c5a7fca756fa9eda2c8615) and [this discussion](https://github.com/pypa/pip/issues/2136#issuecomment-63984482).

**Comment by wolever** [comment]
The most recent version, 0.7.0rc1, should correctly normalize package names.

Would you be able to install it:

    pip install pip2pi==0.7.0rc1

And, if it isn't fixed, can you comment on #55?

Thanks!
