### ISSUE TITLE
Option to not download wheel packages

### ISSUE THREAD

**Issue by Grokzen** [wolever/pip2pi#36]
When using this tool there is no easy way currently to block pip from downloading python wheel packages when using `pip2pi` tool.

Pip have the following flag that can be used when called

```
--no-use-wheel   Do not Find and prefer wheel archives when searching indexes and find-links locations.
```

It would be great if this tool had this option as either a flag to `pip2pi` or perhaps as a environment variable that can be used `NO_WHEEL=true pip2pi ...` or something like that.

**Comment by thijstriemstra** [comment]
Also ran into this issue. [This stackoverflow question](https://stackoverflow.com/questions/21440857/pip2pi-uses-python-3-packages-even-in-a-python-2-virtualenv) seems related.

**Comment by Grokzen** [comment]
I found out that this problem could be mitigated by adding the following to `~/.pip/pip.conf`

```
[global]
use_wheel = False
```

Download of this solutions is that this is global on the entire system and if i want to change back for some other application/use i have to switch back and forth. I still think that this option should be added to pip2pi.

**Comment by wolever** [comment]
D'oh! I'm very sorry, I thought this option was documented somewhere, but apparently it isn't. I'll update the docs now, but in the mean time you can just pass `--no-use-wheel`:

    $ pip2pi /tmp/foo --no-use-wheel pip2pi

**Comment by Grokzen** [comment]
@wolever Saw your commit, thanks :]
