### ISSUE TITLE
Absolute path to target directory on Windows interpreted as remote target

### ISSUE THREAD

**Issue by dalito** [wolever/pip2pi#39]
With this command 
```
pip2pi C:\HTdocs\Fileserver\Programming\Python\pypi_pkgs -n pep8
```

pip2pi interprets the target as remote target and tries to use rsync which fails. The problem is how a remote target is identified, namely by `if ':' in target:`. I solved this by changing the line to `if re.match('.*\..*:', target):`. Since I do not know much about regular expressions, I am not sure if this is a good solution.

Another point: Since rsync is not available on Windows by default, a note about rsync in the requirements section in readme.rst would be helpful.

**Comment by wolever** [comment]
Thanks for the report! I've pushed version 0.6.7 which considers paths matching `/[A-Z]:\\/` to be local.
