### ISSUE TITLE
python 8.1.2 creates problem while installing packages

### ISSUE THREAD

**Issue by zohaibtechknox** [wolever/pip2pi#54]
Hi Recently pip has release its version 8.1.2 which strictly not allow the package names with . like oslo.config . like https://github.com/pypa/pip/issues/3666 . So I have local repository deployed in network which is using pip2pi and I am getting issues installing packages and installing deps with it. That issue was with devpi too but they have now solved it will look at this issue please?

**Comment by WimDeMeester** [comment]
I'm also hitting the same problem...

**Comment by wolever** [comment]
The most recent version, 0.7.0rc1, should correctly normalize package names.

Would you be able to install it:

    pip install pip2pi==0.7.0rc1

And, if it isn't fixed, can you comment on #55?

Thanks!
