### ISSUE TITLE
Pip's "download" command?

### ISSUE THREAD

**Issue by evanandrewrose** [wolever/pip2pi#70]
Does this package do anything different from pip's "download" command? Perhaps it was written before "pip download" was a thing? If so, should this package be deprecated in favor of that command?

**Comment by glensc** [comment]
indeed. the output indicates so as well:

```
Step 8/9 : RUN pip2tgz packages/ tesserocr==2.3.0
 ---> Running in 022e4f9ef3cd
DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be used instead.
```

see https://github.com/wolever/pip2pi/issues/78#issue-346560294

**Comment by safiyat** [comment]
@evanandrewrose This package does do something more than what `pip download` does.
This package builds a local pypa index, path to which can be passed to the `--index-url` switch when installing something using `pip`. Using `pip download` simply downloads the wheel in question to the current working directory, which can't be used as a pypa index.

The package does use `pip download` command internally though, using `pip` as a library.
