### ISSUE TITLE
Is this project dead? Time to fork? …

### ISSUE THREAD

**Issue by kierun** [wolever/pip2pi#79]
[A PR](https://github.com/wolever/pip2pi/pull/75) which fixes #73 and #74  still has not been merged after six months. This point to this project being dead. 

Does anyone have the time to fork it and maintain it?

**Comment by safiyat** [comment]
I could. But will need the community support for it though, of course.

**Comment by safiyat** [comment]
I would still prefer that @wolever revive this project. Maybe add some of us as a collaborator to the project?

**Comment by kierun** [comment]
@wolever has not bothered fixing a critical bug in this code for six months even though there is a PR fixing it. Now, there are good reasons why someone can be away from a project for that long. However, not hearing anything from them, it is hard to judge what those reasons are and what we can do to help. 

We could set up a joint community to fork this… I know it is possible but have not done so.

**Comment by safiyat** [comment]
@wolever is holding an AMA today.

https://twitter.com/SpankChain/status/1047549330817736704

Unfortunately I won't be able to join. Could you join and try to talk to him?

**Comment by sinemetu1** [comment]
We should fork this and move on. We've reached out to @wolever many times with no response. He's active on twitter and apparently doesn't want to maintain this project.

**Comment by wolever** [comment]
Ahh, folks, I'm so sorry :( I have no excuse for the tardiness. Commenting on the PR now.

**Comment by adam820** [comment]
@safiyat That URL may not be the Twitter link you intended to post.

**Comment by safiyat** [comment]
@adam820 I am pretty sure that it is.
